### ISSUE TITLE
Screen Size Hides Buttons And Text Display Issue

### ISSUE THREAD

**Issue by hescrotating** [MontagueM/Charm#14]
Issues viewing text and buttons. Buttons hide on smaller window size. Text cut off at some points. 
![charm size 2](https://user-images.githubusercontent.com/109479786/179418416-10a470a4-2dfb-44e1-a949-db99d960de10.png)
![text cut off](https://user-images.githubusercontent.com/109479786/179418427-76c4fb40-76de-4bfc-8413-a4fc99ab53ec.png)

**Comment by MontagueM** [comment]
thanks, i'm pretty poor at best-practices WPF formatting - definitely something to improve.

**Comment by nath30** [comment]
Similar problem, im guessing due to my screen Scale set higher in windows display settings
![Untitled](https://user-images.githubusercontent.com/61488503/188306181-c4293369-b3ac-46e2-a5b3-3ae06cf553fd.png)
