### ISSUE TITLE
Dumping reticule textures? 

### ISSUE THREAD

**Issue by rlewkowicz** [MontagueM/Charm#143]
I'm not sure I really understand this tool or what people normally use it for. I would like to dump all the reticle textures to pngs.

**Comment by MontagueM** [comment]
is this still an issue? if not will close

**Comment by rlewkowicz** [comment]
Idk. Can I dump reticule textures? I played with this a bit and could not find the assets

**Comment by rlewkowicz** [comment]
They're probably in here. I did some more digging. You wont find a "reticule" folder I don't think. There's just hundreds of these things
