### ISSUE TITLE
Maps do not export with mesh vertex colors

### ISSUE THREAD

**Issue by DeltaDesigns** [MontagueM/Charm#23]
Some static hashes which should (i think) have vc: F8BFB580, 8BAAB580, 05ADB580, B6ABB580

**Comment by MontagueM** [comment]
Yeah VC currently doesn't load on any statics, fix incoming

**Comment by MontagueM** [comment]
entity VC was also kinda broken too, fixed that as well

**Comment by MontagueM** [comment]
Fixed with latest version
