### ISSUE TITLE
Some audio crashes tool when selected

### ISSUE THREAD

**Issue by DeltaDesigns** [MontagueM/Charm#48]
While browsing though audio, the tool will crash on some sounds
[charm.log](https://github.com/MontagueM/Charm/files/9172868/charm.log)
another log just in case
[charm.log](https://github.com/MontagueM/Charm/files/9172869/charm.log)

**Comment by MontagueM** [comment]
i'll stop the crash and log the issue but not sure how to fix

**Comment by MontagueM** [comment]
Implemented crash fix
