### ISSUE TITLE
Textures not auto exporting

### ISSUE THREAD

**Issue by Edragyz** [MontagueM/Charm#54]
Perhaps im super stupid, but despite Gerb's help with the settings, textures aren't being auto exported. Not sure why.

**Comment by MontagueM** [comment]
Can you link:

- charm.log after extracting something to get textures
- charm.exe.config
- a screenshot of the output folder with the fbx in

**Comment by Edragyz** [comment]
Hey so I'm sort of stupid! The mistake I'd made was putting my export folder inside the Charm root folder. This is the first time I've ever had an issue like this. Easiest fix for this is probably just to specify to the user that the export folder MUST be outside the Charm folder.

After changing the location, everything works great.

PS: Never used Github before so I don't know where this thread goes if I close it. I'll just let you close it so you can do whatever it is you want to do with it.

**Comment by MontagueM** [comment]
thanks, useful feedback - I'll add a fix so you can't do that.

**Comment by MontagueM** [comment]
Fixed in v1.1.4
