### ISSUE TITLE
Middle-clicking while viewing maps causes a .net error

### ISSUE THREAD

**Issue by GerbSnail** [MontagueM/Charm#68]
What it says in the title, while inspecting maps, I accidentally middle-clicked and it caused this error to pop up:

![image](https://user-images.githubusercontent.com/91706089/183486544-0878e4a6-2287-4535-bd53-cdb5c229397c.png)

Clicking continue allows the program to keep going and possibly could still extract things, but if you were to middle click again it would completely crash the program. I don't know if the issue was just from this previous update because I was updating from 1.15, but it should definitely be looked into because I'm sure I'm not the only one who turns their brain off and accidentally tries middle-click to move the camera like in Blender/UE

**Comment by MontagueM** [comment]
yea this is a new issue, fixed in next update thanks!

**Comment by MontagueM** [comment]
i've also focused the middle click close to the tab only
