### ISSUE TITLE
Investment Crash

### ISSUE THREAD

**Issue by easyskanka** [MontagueM/Charm#74]
Tried on all versions of Charm, Cant get past investment

[charm.log](https://github.com/MontagueM/Charm/files/9441163/charm.log)

D2 is installed on my C drive, its the only thing installed in the steamapps folder for better gameplay on my stream

have tried to install charm on all my drives but still no success

**Comment by MontagueM** [comment]
Honestly no clue, can't help here as seems like no one else has the issue and cannot be reproduced

**Comment by MontagueM** [comment]
In fact I was able to replicate it, I'll see if I can figure it out

**Comment by MontagueM** [comment]
ok i think i got what causes it, there are many things combined but the final thing is you cannot keep old packages in the destiny 2 directory - sometimes it doesnt delete them from your work space, especially if you use depot downloader or similar, and in doing so it will leave some packages left over that might not work - there are some approaches i could take to fix this, but none are really clean and nice

 im not sure on any clean and concise way to manage this but the cleanest would be to just delete all the pkgs and redownload the game

or you could go through investment and delete all the packages that were meant to be removed via steamdb - could probably make a script to do this eg 8207814430234758153 in https://steamdb.info/depot/1085661/history/

 all the _7/_8/_9 cause errors bc they have a higher patch number but should be deleted, so charm thinks theyre the newer patch but theyre missing info

 actually yea easiest way would be to write a python script that takes the most recent manifest file and wipes all the old packages from the directory

 i can probably code smth quick that will do it


```
import os
# go to https://steamdb.info/depot/1085661/ -> files -> show all, then ctrl + s the page
name = r"C:/Users/monta/Downloads/Game Depot (Depot 1085661) · SteamDB.htm"
pkgs_path = r"I:\SteamLibrary\steamapps\common\Destiny 2\packages"
auto_delete = True

packages = []
with open(name, "r", encoding="utf8") as f:
    for l in f.readlines():
        if ".pkg" in l:
            pkg = l.split(">")[1].split("<")[0]
            packages.append(pkg.split("/")[1])

for p in os.listdir(pkgs_path):
    if p not in packages and "_en_" not in p:
        print(f"{p} missing")
        if auto_delete:
            os.remove(f"{pkgs_path}/{p}")
            print(f"Removed {p}")
```


an it on mine and it fixed the problem, although if you have a language other than english it will delete the files + make sure to delete paths.cache
