### ISSUE TITLE
Issue in ~\Charm\Field\General\Tag.cs Line 332

### ISSUE THREAD

**Issue by abdtamimi98** [MontagueM/Charm#95]
Hello, in Line 335, Exception occurred after the release of Season 19 
The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'

**Comment by MontagueM** [comment]
Known, will be fixed

**Comment by MontagueM** [comment]
Fixed in v1.3.1
