### ISSUE TITLE
I'm sorry but Charm is still crashing

### ISSUE THREAD

**Issue by Genevahu** [MontagueM/Charm#96]
I'm sorry but I had the same problem in 1.3.1 like 1.3.0：

> System.Threading.Tasks.ParallelSystem.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')

Is there something wrong with my operation? This is my charm log

Thank you for all your hard work
[charm.log](https://github.com/MontagueM/Charm/files/10201562/charm.log)

**Comment by MontagueM** [comment]
Should be actually fixed now, please redownload v1.3.1 and let me know of any further issues if you find them

**Comment by MontagueM** [comment]
@Genevahu lmk if fixed

**Comment by Genevahu** [comment]
It's work,Thanks again for all your hard work,I'm sorry I couldn't inform you in time due to the time difference.
